[pytest]
addopts =
    -m login
    --html=Reports/temp.html
markers =
    login: Login related test cases
    registration: Registration related test cases
    product_add_to_cart: Product add to cart related test cases
    database: database related test cases
    products_add_to_cart: product add to cart
    smoke: smoke related test case


